/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jtorrent;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramSocket;
import java.net.Inet6Address;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.URL;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // try {
        // URL url_name = new URL("http://bot.whatismyipaddress.com");

        // BufferedReader sc = new BufferedReader(new
        // InputStreamReader(url_name.openStream()));

        // // reads system IPAddress
        // String systemipaddress = sc.readLine().trim();
        // System.out.println(systemipaddress);
        // }
        // try {
        // InetAddress[] addresses =
        // InetAddress.getAllByName("2405:204:9003:d13:38b8:377f:228a:8f8");
        // for (InetAddress addr : addresses) {
        // if (addr instanceof Inet6Address) {
        // System.out.println(addr);
        // }
        // }
        // }
        // // try (final DatagramSocket socket = new DatagramSocket()) {
        // // socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
        // // String ip = ((Inet6Address) socket.getLocalAddress()).getHostAddress();
        // // System.out.println(ip);
        // catch (IOException e) {
        // e.printStackTrace();
        // }
    }
}
